#+TITLE: Starter Kit Spelling
#+OPTIONS: toc:nil num:nil ^:nil

This is part of the [[file:starter-kit.org][Emacs Starter Kit]].

* Starter Kit Hunspell
Hackish file to accommodate having Hunspell installed on your Mac. Otherwise
flyspell doesn't start properly. Putting this customization in
<username>.org initiates it too late. 

- This file is loaded by a special line added to [[file:starter-kit.org][starter-kit.org]]. 

** Specify Hunspell

You'll need to have Hunspell dictionaries on your system. MacOS comes with these but they are quite outdated. Get the recent versions LibreOffice's [[https://github.com/LibreOffice/dictionaries][dictionaries repo]] and save them under a folder which Hunspell recognizes (on MacOS =~/Library/Spelling=, otherwise see =hunspell -D=), or set the =DICPATH= environmental variable to find dictionaries.

#+begin_src emacs-lisp
   (require 'flyspell)
   (add-to-list 'ispell-dictionary-alist '("hu_HU"
                                           "[[:alpha:]]"
                                           "[^[:alpha:]]"
                                           "[']"
                                           t
                                           ("-d" "hu_HU")
                                           nil
                                           utf-8))
  (add-to-list 'ispell-dictionary-alist '("en_GB"
                                          "[[:alpha:]]"
                                          "[^[:alpha:]]"
                                          "[']"
                                          t
                                          ("-d" "en_GB")
                                          nil
                                          utf-8))
  (add-to-list 'ispell-dictionary-alist '("en_US"
                                          "[[:alpha:]]"
                                          "[^[:alpha:]]"
                                          "[']"
                                          t
                                          ("-d" "en_US")
                                          nil
                                          utf-8))
  (setq ispell-program-name "hunspell")
  (setq ispell-dictionary "hu_HU") 
  ;; (setq ispell-personal-dictionary "~/.aspell.en.pws")
  (setq flyspell-issue-message-flag nil)

  ;; Select suggestions using right-clicks

  (eval-after-load "flyspell"
  '(progn
     (define-key flyspell-mouse-map [down-mouse-3] #'flyspell-correct-word)
     (define-key flyspell-mouse-map [mouse-3] #'undefined)))


  ;; More efforts to speed up flyspell
  ;; See http://www.brool.com/index.php/speeding-up-flyspell-region 
    (defadvice flyspell-region (around fast-flyspell-region)
      (cl-flet ( (sit-for (x) t) ) 
        ad-do-it))
    (ad-activate 'flyspell-region)

#+end_src


** Easily switch languages

Cycle between often used dictionaries (via [[https://www.emacswiki.org/emacs/FlySpell][Diogo Ramos]] on
EmacsWiki). For other dictionaries, use =M-x ispell-change-dictionary=.

#+begin_src emacs-lisp
  (let ((langs '("hu_HU" "en_GB")))
    (setq lang-ring (make-ring (length langs)))
    (dolist (elem langs) (ring-insert lang-ring elem)))
  (defun cycle-ispell-languages ()
    (interactive)
    (let ((lang (ring-ref lang-ring -1)))
      (ring-insert lang-ring lang)
      (ispell-change-dictionary lang)))
  (global-set-key (kbd "C-c d") 'cycle-ispell-languages)
#+end_src


** Automatically guess the language

#+begin_src emacs-lisp
  (require 'guess-language)
  (setq guess-language-languages '(hu en))
  (setq guess-language-langcodes
    '((en . ("en_GB" "English"))
      (hu . ("hu_HU" nil))))

  (add-hook 'text-mode-hook (lambda () (guess-language-mode 1)))
#+end_src


#+source: message-line
#+begin_src emacs-lisp
  (message "Starter Kit Spelling loaded.")
#+end_src
